import img2 from "./img/image.png";
import img3 from "./img/img2.png";
import img4 from "./img/img3.png";
import kidimg from "../Product/img/kid-img.webp";
import menimg from "../Product/img/men-img.webp";
import hatimg from "../Product/img/hat-img.jpg";
import bagimg from "../Product/img/bags.webp";

export const products = [
  {
    id: 1,
    name: "Dress 1",
    category: "Womens",
    image: img2.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 2,
    name: "Dress 2",
    category: "Kids",
    image: kidimg.src,
    description: "Fit: Description 2",
    price: 64.99,
    iscart: false,
  },
  {
    id: 3,
    name: "Dress 3",
    category: "Mens",
    image: menimg.src,
    description: "Fit: Description 3",
    price: 14.99,
    iscart: false,
  },
  {
    id: 4,
    name: "Dress 4",
    category: "Mens",
    image: menimg.src,
    description: "Fit: Description 4",
    price: 94.99,
    iscart: false,
  },
  {
    id: 5,
    name: "Dress 5",
    category: "Womens",
    image: img3.src,
    description: "Fit: Description 5",
    price: 64.99,
    iscart: false,
  },
  {
    id: 6,
    name: "Dress 6",
    category: "Kids",
    image: kidimg.src,
    description: "Fit: Description 6",
    price: 55.99,
    iscart: false,
  },
  {
    id: 7,
    name: "Dress 7",
    category: "Mens",
    image: menimg.src,
    description: "Fit: Description 7",
    price: 104.99,
    iscart: false,
  },
  {
    id: 8,
    name: "Dress 8",
    category: "Womens",
    image: img2.src,
    description: "Fit: Description 8",
    price: 23.99,
    iscart: false,
  },
  {
    id: 9,
    name: "Dress 9",
    category: "Womens",
    image: img4.src,
    description: "Fit: Description 9",
    price: 34.99,
    iscart: false,
  },
  {
    id: 10,
    name: "Dress 10",
    category: "Mens",
    image: menimg.src,
    description: "Fit: Description 10",
    price: 59.99,
    iscart: false,
  },
  {
    id: 11,
    name: "Dress 11",
    category: "Kids",
    image: kidimg.src,
    description: "Fit: Description 11",
    price: 510.99,
    iscart: false,
  },
  {
    id: 12,
    name: "Womens",
    category: "Womens",
    image: img2.src,
    description: "Fit: Description 12",
    price: 14.99,
    iscart: false,
  },
  {
    id: 13,
    name: "Dress 13",
    category: "Mens",
    image: menimg.src,
    description: "Fit: Description 13",
    price: 24.99,
    iscart: false,
  },
  {
    id: 14,
    name: "Dress 14",
    category: "Womens",
    image: img4.src,
    description: "Fit: Description 14",
    price: 234.99,
    iscart: false,
  },
  {
    id: 15,
    name: "Dress 15",
    category: "Womens",
    image: img3.src,
    description: "Fit: Description 15",
    price: 54.99,
    iscart: false,
  },
  {
    id: 16,
    name: "Dress 16",
    category: "Bags",
    image: bagimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 17,
    name: "Dress 17",
    category: "ACCESSORIES",
    image: hatimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 18,
    name: "Dress 18",
    category: "Bags",
    image: bagimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 19,
    name: "Dress 19",
    category: "Bags",
    image: bagimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 20,
    name: "Dress 20",
    category: "ACCESSORIES",
    image: hatimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
  {
    id: 21,
    name: "Dress 21",
    category: "ACCESSORIES",
    image: hatimg.src,
    description: "Fit: Description 1",
    price: 54.99,
    iscart: false,
  },
];
