import type { Metadata } from "next";

import "./globals.css";

import Footer from "@/Component/Shared/Footer/Footer";
import Navbar from "@/Component/Shared/Header/Navbar";
import Testimonial from "@/Component/Shared/Testimonial/Testimonial";
import Cta from "@/Component/Shared/CTA/Cta";
import FAQ from "@/Component/Shared/FAQ/Faq";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Testimonial />
        <FAQ />
        <Cta />

        <Footer />
      </body>
    </html>
  );
}
